apiVersion: v1
kind: Pod
metadata:
  name: cpu-7zip
  labels:
    app: cpu-7zip
spec:
  restartPolicy: Never
  nodeName: raspberrypi
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-output
  containers:
    - name: cpu-7zip
      image: 533062264855.dkr.ecr.sa-east-1.amazonaws.com/k3s:cpu-7zip
      imagePullPolicy: Always
      volumeMounts:
        - name: pv-storage
          mountPath: /mnt/output
  imagePullSecrets:
    - name: regcred

