apiVersion: v1
kind: Pod
metadata:
  name: iozone
  labels:
    app: iozone
spec:
  restartPolicy: Never
  nodeName: raspberrypi
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-output
  containers:
    - name: iozone
      image: 533062264855.dkr.ecr.sa-east-1.amazonaws.com/k3s:iozone
      imagePullPolicy: Always
      volumeMounts:
        - name: pv-storage
          mountPath: /mnt/output
  imagePullSecrets:
    - name: regcred
